(use spork/test ../gp/data/schema)

(import ../gp/environment/app)
(start-suite "Documentation")
(assert-docs "../gp/environment/app")
(end-suite)

(start-suite "HTTP")
(assert ((?eq "a=b") (app/process-body "a=b")) "Process string body")
(assert ((?eq "a=b") (app/process-body {:a "b"})) "Process dict body")
(assert ((?deep-eq @{:a "b"}) (app/coerce-body {"a" " b "})) "Coerce body")
(end-suite)

(start-suite "Events")
(assert (((app/Dirty :update) nil @{}) :dirty) "Dirty sets flag")
(assert-not (((app/Clean :update) nil @{:dirty true}) :dirty) "Clean unsets flag")
(assert-not ((app/Present :watch) nil {:http "localhost:80" :rpc {:url "localhost:90"}} nil) "Present without log?")
(assert ((?long 2) ((app/Present :watch) nil {:http "localhost:80" :rpc {:url "localhost:90"} :log true} nil)) "Present both with log?")
(assert ((?long 1) ((app/Present :watch) nil {:rpc {:url "localhost:90"} :log true} nil)) "Present one with log?")
(end-suite)

(start-suite "Test helpers")
(assert (app/success? {:status 200}) "HTTP success?")
(assert ((app/success-has? "pepe")
          {:status 200 :body "pepe"}) "HTTP success has in body")
(assert ((app/success-has-not? "pepe")
          {:status 200 :body "prepe"}) "HTTP success has not in body")
(assert ((app/redirect? "/home")
          {:status 303 :headers {"content-length" "0" "location" "/home"}}) "HTTP redirect?")
(assert (app/empty-success? {:status 200 :body ""}) "HTTP empty success?")
(end-suite)
