(use spork/test)
(import /build/gp/codec)
(start-suite "Documentation")
(assert-docs "/build/gp/codec")
(end-suite)
(start-suite "base64")
(assert (= (codec/base64/encode "Ahoj") "QWhvag==") "encode")
(assert (= (codec/base64/decode "QWhvag==") "Ahoj") "decode")
(end-suite)
