(use spork/test jhydro)
(import gp/compute)
(import gp/compute/cpp)
(import gp/compute/opencl)
(import gp/linalg)

(start-suite "Linalg documentation")
(assert-docs "gp/linalg")
(end-suite)

(def host (cpp/engine))

(start-suite "Linalg vectors")

(def x (linalg/vctr host :f32 [1 2 3]))
(assert (linalg/linalg? x) "linalg value")
(assert (linalg/vector? x) "vector predicate")
(assert (not (linalg/matrix? x)) "vector is not a matrix")
(assert (not (linalg/linalg? {:structure :vctr})) "foreign struct rejected")
(assert (= :vctr (linalg/structure x)) "vector structure")
(assert (= :f32 (linalg/dtype x)) "vector dtype")
(assert (= "cpp" (compute/engine-name (linalg/engine x))) "vector engine")
(assert (= 3 (linalg/dim x)) "vector dimension")
(assert (= 2 (linalg/entry x 1)) "vector entry")
(linalg/entry! x 1 9)
(assert (deep= @[1 9 3] (linalg/to-array x)) "vector write")
(assert-error "vector entry takes one index" (linalg/entry x 1 2))
(assert-error "vector bounds" (linalg/entry x 3))
(assert-error "vector negative bounds" (linalg/entry x -1))
(assert-error "dim rejects matrices" (linalg/dim (linalg/ge host :f32 1 1 [1])))

(def sub (linalg/subvector x 1 2))
(assert (linalg/vector? sub) "subvector value")
(assert (= 2 (linalg/dim sub)) "subvector dimension")
(assert (= (compute/storage-id (linalg/view x))
           (compute/storage-id (linalg/view sub)))
        "subvector shares storage")
(linalg/entry! sub 0 7)
(assert (deep= @[1 7 3] (linalg/to-array x)) "subvector writes through")

(end-suite)

(start-suite "Linalg general matrices")

(def a (linalg/ge host :f32 2 3 [1 2 3 4 5 6]))
(assert (linalg/matrix? a) "matrix predicate")
(assert (= :ge (linalg/structure a)) "general structure")
(assert (= 2 (linalg/mrows a)) "matrix rows")
(assert (= 3 (linalg/ncols a)) "matrix columns")
(assert (= 6 (linalg/entry a 1 2)) "matrix entry")
(assert-error "matrix entry takes two indexes" (linalg/entry a 1))
(assert-error "matrix row bounds" (linalg/entry a 2 0))
(assert-error "matrix column bounds" (linalg/entry a 0 3))
(assert-error "uplo rejects general matrices" (linalg/uplo a))

(def at (linalg/trans a))
(assert (= :ge (linalg/structure at)) "transpose stays general")
(assert (= 3 (linalg/mrows at)) "transposed rows")
(assert (= 2 (linalg/ncols at)) "transposed columns")
(assert (= 6 (linalg/entry at 2 1)) "transposed entry")
(assert (= (compute/storage-id (linalg/view a))
           (compute/storage-id (linalg/view at)))
        "transpose is zero-copy")
(assert-error "trans rejects vectors" (linalg/trans x))

(assert (deep= @[1 2 3] (linalg/to-array (linalg/row a 0))) "row view")
(assert (deep= @[2 5] (linalg/to-array (linalg/col a 1))) "column view")
(linalg/entry! (linalg/col a 1) 0 20)
(assert (= 20 (linalg/entry a 0 1)) "column view writes through")
(assert-error "row bounds" (linalg/row a 2))
(assert-error "column bounds" (linalg/col a 3))

(end-suite)

(start-suite "Linalg structured matrices")

(def t (linalg/tr host :f32 2 [1 99 2 3]))
(assert (= :tr (linalg/structure t)) "triangular structure")
(assert (= :lower (linalg/uplo t)) "default uplo")
(assert (not (linalg/unit-diag? t)) "default diagonal")
(assert (= 0 (linalg/entry t 0 1)) "unstored triangle reads zero")
(assert (= 2 (linalg/entry t 1 0)) "stored triangle reads storage")
(assert (deep= @[1 0 2 3] (linalg/to-array t)) "logical triangular contents")
(assert-error "unstored triangle rejects writes" (linalg/entry! t 0 1 5))
(assert-error "invalid uplo" (linalg/tr host :f32 2 [1 0 2 3] :diagonal))
(assert-error "invalid diag" (linalg/tr host :f32 2 [1 0 2 3] :lower :odd))

(def unit (linalg/tr host :f32 2 [99 0 2 99] :lower :unit))
(assert (linalg/unit-diag? unit) "unit diagonal predicate")
(assert (= 1 (linalg/entry unit 0 0)) "unit diagonal reads one")
(assert (deep= @[1 0 2 1] (linalg/to-array unit)) "logical unit contents")
(assert-error "unit diagonal rejects writes" (linalg/entry! unit 0 0 5))

(def tt (linalg/trans t))
(assert (= :upper (linalg/uplo tt)) "transpose flips the triangle")
(assert (= 2 (linalg/entry tt 0 1)) "transposed stored entry")
(assert (= 0 (linalg/entry tt 1 0)) "transposed implicit zero")
(assert (deep= @[1 2 0 3] (linalg/to-array tt)) "logical transposed contents")

(def s (linalg/sy host :f32 2 [1 99 2 3]))
(assert (= :sy (linalg/structure s)) "symmetric structure")
(assert (= 2 (linalg/entry s 0 1)) "mirrored entry")
(assert (deep= @[1 2 2 3] (linalg/to-array s)) "logical symmetric contents")
(assert-error "mirror rejects writes" (linalg/entry! s 0 1 5))
(linalg/entry! s 1 0 4)
(assert (= 4 (linalg/entry s 0 1)) "stored write updates the mirror")
(assert (= s (linalg/trans s)) "symmetric matrix is its own transpose")

(def d (linalg/gd host :f32 3 [1 2 3]))
(assert (= :gd (linalg/structure d)) "diagonal structure")
(assert (= 3 (linalg/mrows d)) "diagonal rows")
(assert (= 2 (linalg/entry d 1 1)) "diagonal entry")
(assert (= 0 (linalg/entry d 0 2)) "off-diagonal reads zero")
(assert (deep= @[1 0 0 0 2 0 0 0 3] (linalg/to-array d))
        "logical diagonal contents")
(assert-error "off-diagonal rejects writes" (linalg/entry! d 0 1 5))
(assert-error "diagonal length must match" (linalg/gd host :f32 3 [1 2]))
(assert (= d (linalg/trans d)) "diagonal matrix is its own transpose")
(assert-error "row views need general structure" (linalg/row t 0))
(assert-error "unit-diag? rejects other structures" (linalg/unit-diag? s))

(end-suite)

(start-suite "Linalg transfer")

(def moved (linalg/transfer host t))
(assert (= :tr (linalg/structure moved)) "transfer preserves structure")
(assert (= :lower (linalg/uplo moved)) "transfer preserves uplo")
(assert (not (linalg/unit-diag? moved)) "transfer preserves diag")
(assert (deep= (linalg/to-array t) (linalg/to-array moved))
        "transfer preserves contents")
(assert (not= (compute/storage-id (linalg/view t))
              (compute/storage-id (linalg/view moved)))
        "transfer copies storage")

(def moved-tt (linalg/transfer host tt))
(assert (= :upper (linalg/uplo moved-tt))
        "transferred transpose keeps the flipped triangle")
(assert (deep= (linalg/to-array tt) (linalg/to-array moved-tt))
        "transferred transpose preserves logical contents")

(when (opencl/available?)
  (def gpu (opencl/engine))
  (def device-a (linalg/transfer gpu a))
  (assert (= "opencl" (compute/engine-name (linalg/engine device-a)))
          "device value engine")
  (assert (= :ge (linalg/structure device-a)) "device structure")
  (assert (deep= (linalg/to-array a) (linalg/to-array device-a))
          "device contents")
  (def device-s (linalg/transfer gpu s))
  (assert (= :lower (linalg/uplo device-s)) "device uplo")
  (assert (deep= (linalg/to-array s) (linalg/to-array device-s))
          "device symmetric logical contents")
  (assert (= 4 (linalg/entry device-s 0 1)) "device mirrored entry")
  (def round-trip (linalg/transfer host device-a))
  (assert (deep= (linalg/to-array a) (linalg/to-array round-trip))
          "round trip"))

(end-suite)
