(use spork/test)
(import gp/net/server)
(import gp/net/rpc)

(unless (= :windows (os/which))
  (start-suite :unix-rpc)
  (def dir (string "/tmp/gp-rpc-socket-" (os/getpid)))
  (os/mkdir dir)
  (os/chmod dir 8r700)
  (def path (string dir "/rpc.sock"))
  (def psk "bow-test-only-isolated-rpc-key!!")
  (def channel (ev/chan 8))
  (def [_ listener] (server/start channel :unix path))
  (def handling (rpc/on-connection @{:psk psk :echo (fn [_ value] value)}))
  (def worker (ev/go (fn [] (rpc/supervisor channel handling))))
  (def client (rpc/client :unix path "socket-test" psk))
  (assert (= {:invoice "2401"} (ev/with-deadline 2 (:echo client {:invoice "2401"})))
          "Encrypted RPC carries structured values over a Unix socket")
  (:close client)
  (:reopen client)
  (assert (= :reopened (ev/with-deadline 2 (:echo client :reopened)))
          "The same RPC client reopens a Unix endpoint")
  (:close client)
  (server/close listener)
  (ev/sleep 0.01)
  (def [_ successor] (server/start channel :unix path))
  (:open client)
  (assert (= :restarted (ev/with-deadline 2 (:echo client :restarted)))
          "An RPC client reconnects after listener replacement")
  (:close client)
  (server/close successor)
  (ev/sleep 0.01)
  (ev/chan-close channel)
  (ev/sleep 0.01)
  (end-suite)
  (each file (os/dir dir) (os/rm (string dir "/" file)))
  (os/rmdir dir))
