(use spork/test)
(import gp/net/server)
(import gp/net/socket)

(start-suite :endpoints)
(assert-docs "gp/net/socket")
(assert (deep= [:unix "/tmp/bill.sock"] (server/host-port "unix:/tmp/bill.sock")))
(assert (deep= ["localhost" "8888"] (server/host-port "localhost:8888")))
(assert (= "unix:/tmp/bill.sock" (server/address {:host :unix :port "/tmp/bill.sock"})))
(assert (= "localhost:8888" (server/address {:host "localhost" :port "8888"})))
(each invalid ["unix:" "unix:relative.sock" "unix:@abstract" "localhost" "localhost:abc"
               "localhost:65536" "unix:/tmp/\0bad.sock" "unix:/tmp/../a.sock"
               "unix:/tmp//a.sock" "unix:/tmp/./a.sock" "unix:/tmp/a.sock/"]
  (assert-not (server/address? invalid) (string "Invalid endpoint refused: " invalid)))
(end-suite)

(unless (= :windows (os/which))
  (def dir (string "/tmp/gp-socket-test-" (os/getpid)))
  (os/mkdir dir)
  (os/chmod dir 8r700)
  (def path (string dir "/door.sock"))
  (start-suite :socket-ownership)
  (def first (socket/listen path))
  (assert (= 8r600 (os/stat path :int-permissions)) "RPC sockets default to owner-only")
  (assert-error "A second owner cannot displace a live socket" (socket/listen path))
  (socket/close first)
  (assert-not (os/lstat path) "Graceful close removes the socket path")
  (assert (os/stat (string path ".lock")) "The stable lock inode remains")
  (def second (socket/listen path 8r660))
  (socket/close first)
  (assert (= 8r660 (os/stat path :int-permissions)) "HTTP may share its socket with nginx")
  (let [connection (net/connect :unix path)]
    (assert connection "A repeated old close cannot unlink the successor")
    (:close connection))
  (socket/close second)
  (spit path "keep this file")
  (assert-error "A regular file is never removed" (socket/listen path))
  (assert (= "keep this file" (string (slurp path))))
  (os/rm path)
  (def unmanaged (net/listen :unix path))
  (assert-error "A listener without a gp claim is still protected" (socket/listen path))
  (let [connection (net/connect :unix path)]
    (assert connection "The unmanaged listener is still reachable")
    (:close connection))
  (:close unmanaged)
  (os/rm path)
  (end-suite)

  (start-suite :handover)
  (def channel (ev/chan 8))
  (def [_ listener] (server/start channel :unix path))
  (def client (net/connect :unix path))
  (def [_ accepted] (ev/take channel))
  (server/close listener)
  (def successor (socket/listen path))
  (:write accepted "handover")
  (assert (= "handover" (string (:read client 8)))
          "The accepted response survives releasing the old listener")
  (:close accepted)
  (:close client)
  (socket/close successor)
  (ev/chan-close channel)
  (end-suite)

  (start-suite :refused-descriptor)
  (defn reachable? []
    (def [ok connection] (protect (socket/connect :unix path)))
    (when ok (:close connection))
    ok)
  # A guardian that hands its door over and takes it back listens again on
  # the number its last listener had. Nothing may close that number later.
  (def handed (socket/listen path))
  (socket/close handed)
  (def taken-back (socket/listen path))
  (gccollect)
  (assert (reachable?) "A listener taken back survives the collector")
  (socket/close taken-back)
  (def stale (net/listen :unix path :stream true))
  (:close stale)
  (assert-error "A stale socket refuses" (socket/connect :unix path))
  (os/rm path)
  (def after-refusal (socket/listen path))
  (gccollect)
  (assert (reachable?) "A listener opened after a refusal survives the collector")
  (socket/close after-refusal)
  (end-suite)

  (start-suite :crash-recovery)
  (def child
    (os/spawn [(dyn *executable* "janet") "-e"
               (string/format
                 "(import gp/net/socket) (def listener (socket/listen %q)) (prin \"r\") (file/flush stdout) (ev/sleep 60)"
                 path)] :p {:out :pipe :in :pipe}))
  (ev/with-deadline 5 (:read (child :out) 1))
  (assert-error "A separate process owns the socket" (socket/listen path))
  (os/proc-kill child)
  (os/proc-wait child)
  (os/proc-close child)
  (assert (= :socket (os/lstat path :mode)) "A killed process leaves a stale socket")
  (def recovered (socket/listen path))
  (let [connection (net/connect :unix path)]
    (assert connection "The stale socket is recovered after process death")
    (:close connection))
  (socket/close recovered)
  (end-suite)
  (each file (os/dir dir) (os/rm (string dir "/" file)))
  (os/rmdir dir))
