(use spork/test spork/misc)
(import ../gp/data/store)
(start-suite "Documentation")
(assert-docs "../gp/data/store")
(end-suite)

(start-suite "Simple store")
(assert (def s (make store/Store)) "make store")
(assert (:init s) "init store")
(assert (:put s true :a :b) "put into store")
(assert (:get s :a :b) "get from store")
(assert (:flush s) "")
(assert (:get (:init (make store/Store)) :a :b))
(assert (not (:get (:init (make store/Store)) :c)))
(end-suite)

(start-suite "Ident store")
(assert (def s (make store/IdentityStore)) "make store")
(assert (:init s) "init store")
(assert (:put s @{:uuid "1"} :a) "put into store")
(assert (= "1" (:get s :a :uuid)) "get from store")
(assert (deep= (:geti s "1") @{:uuid "1"}) "identity get")
(assert (not (:geti s "2")) "nil nonexistent uuid")
(end-suite)
