(use spork/test spork/misc)
(import ../gp/data/store)
(start-suite "Documentation")
(assert-docs "../gp/data/store")
(end-suite)

(start-suite "Simple store")
(def s (make store/Store))
(assert s "make store")
(assert (:init s) "init store")
(assert (:put s true :a :b) "put into store")
(assert (:get s :a :b) "get from store")
(assert (:flush s) "")
(assert (:get (:init (make store/Store)) :a :b))
(assert (not (:get (:init (make store/Store)) :c)))
(end-suite)

(start-suite "Ident store")
(def s (make store/IdentityStore))
(def thing @{:uuid "1"})
(assert s "make identity store")
(assert (:init s) "init store")
(assert (:put s thing :a :b) "put into store")
(assert (= (:get s :a :b) thing) "get from store")
(assert (= (:geti s "1") thing) "identity get")
(assert (= (:geti s "1") (:get s :a :b)) "identity get")
(assert (nil? (:geti s "2")) "nil nonexistent uuid")
(assert (= (:getp s "1") [:a :b]) "path get")
(end-suite)
