(use spork/test)
(import /build/gp/term)

(assert-docs "/build/gp/term")
(start-suite)
(assert-no-error
  (defer (term/shutdown)
    (term/init)
    (assert (> (term/width) 0) "width")
    (assert (> (term/height) 0) "height")
    (def x (math/floor (/ (term/width) 2)))
    (def y (math/floor (/ (term/height) 2)))
    (term/set-cursor x y)
    (term/hide-cursor)
    (term/set-cell x y (chr "a") 0 0)
    (term/print x y 0 0 "Ho ho ho")
    (term/present)
    (assert (not (nil? term/poll)))))
(end-suite)
