(use spork/test)
(import /build/gp/tui)

(assert-docs "/build/gp/tui")
(start-suite "low level")
(defer (tui/shutdown)
  (tui/init)
  (assert (> (tui/width) 0) "width")
  (assert (> (tui/height) 0) "height")
  (def x (math/floor (/ (tui/width) 2)))
  (def y (math/floor (/ (tui/height) 2)))
  (tui/set-cursor x y)
  (tui/hide-cursor)
  (tui/set-cell x y (chr "a") 0 0)
  (tui/print x y 0 0 "Ho ho ho")
  (tui/present))
(end-suite)
(start-suite "screen")
(comment (screen
           (each i (range (tui/height))
             (tui/at i i)
             (tui/put "a")
             ())))
(end-suite)
