image: alpine/latest
triggers:
  - action: email
    condition: failure
    to: "<pe@pan.earth>"
secrets:
- cc1a3890-4696-48f6-bc12-f73d87dd0f20
sources:
- https://github.com/janet-lang/spork.git
- git@git.sr.ht:~pepe/gp
tasks:
  - janet: |
        sudo apk add janet janet-dev
  - spork: |
        cd spork
        sudo janet --install .
  - gp: |
        cd gp
        sudo /usr/lib/janet/bin/janet-pm deps
        /usr/lib/janet/bin/janet-pm build
        sudo /usr/lib/janet/bin/janet-pm install
        /usr/lib/janet/bin/janet-pm test

